name: "Ship Loud Export"
on:
  push:
    branches: [ 'test' ]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eddspire/action.shiploud.so@v1.0.2
        with:
          api-token: ${{ secrets.SHIPLOUD_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
